#this is developmental version of configurations

server:
  port: 8083

#database connections
spring:
  datasource:
    url: jdbc:mysql://local:3306/auth_app_yt
    username: root
    password: root1234

#    hikari:
#      pool_name: HikariCP
#      maximum-pool-size: 5
#      connection_timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 1800000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1
#spring and hibernate configurations

jpa:
  hibernate:
    ddl-auto: update    #automatically table will ge updated when entities are there
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  show-sql: true

